### ISSUE TITLE
Add CI for the project

### ISSUE THREAD

**Issue by Bounz** [TinkoffCreditSystems/Horarium#10]
I think it'd be great to add CI to this project to automate builds, pull request checks (style and static code analysis) and push NuGet packages to MyGet and NuGet.

**Comment by Bobreshovr** [comment]
CI is added with check PR and push to Nuget - https://cloud.drone.io/TinkoffCreditSystems/Horarium/ 
Next step is to add code coverage, I'm choosing between https://codecov.io and https://coveralls.io/

**Comment by Bounz** [comment]
Oh, sorry, missed that.
Coveralls.io looks more popular, but I prefer codecov.io.
Also take a look at https://www.codefactor.io, some analog of SonarQube.

**Comment by Bobreshovr** [comment]
Added codecove.io to project https://codecov.io/gh/TinkoffCreditSystems/Horarium
What about app github from codecove.io? Is it a convenient one?
