### ISSUE TITLE
More integration tests

### ISSUE THREAD

**Issue by itrofimow** [TinkoffCreditSystems/Horarium#20]
I feel like we should have more integration tests - there are currently only 2 of 'em, and their coverage of scheduling logic seems lacking to me (especially in multithreaded environment).

There are currently 2 open issues about different from MongoDb repositories and in case someone would implement any of those neither they or we can be sure about correctness of the implementation.

It would be really nice to have some load tests as well :)

**Comment by Bobreshovr** [comment]
It's a good idea. I think we need to refactor integration tests. We need more isolated tests. I have an idea about it. 
First is it runs tests for every DB in a different process.

**Comment by itrofimow** [comment]
> First is it runs tests for every DB in a different process.

Yea, this might be a good solution, i like this idea.

@Bobreshovr I guess we could sit together and make somewhat of a plan for building good integration tests, which we could then document here and follow

**Comment by Bobreshovr** [comment]
add #29
