### ISSUE TITLE
HorariumLogger does not output actual exception

### ISSUE THREAD

**Issue by Tolyandre** [TinkoffCreditSystems/Horarium#23]
When using `Horarium.AspNetCore` errors are logged without actual exception.
![image](https://user-images.githubusercontent.com/2414704/59761050-d194ea00-92a4-11e9-98bc-fa064db899cd.png)

It seems that `HorariumLogger.cs` puts params in wrong order:
`  _logger.LogError(message, ex);`

Expected:
` _logger.LogError(ex, message);`

**Comment by Bounz** [comment]
It would be nice if you will be able to provide a PR with a fix for this issue.
