### ISSUE TITLE
Jobs implementing IAllRepeatesIsFailed dont behave as expected if FailedEvent(object param, Exception ex) throws

### ISSUE THREAD

**Issue by itrofimow** [TinkoffCreditSystems/Horarium#34]
So it seems that if implementation of `IAllRepeatesIsFailed.FailedEvent(object param, Exception ex)` throws, job gets reschedules till forever, thus ignoring repeat strategy.

Probably we should wrap this https://github.com/TinkoffCreditSystems/Horarium/blob/master/src/Horarium/Handlers/ExecutorJob.cs#L135 into try {} catch {}

**Comment by Bobreshovr** [comment]
It's a good idea. I'm waiting for PR

**Comment by itrofimow** [comment]
Should be ok now
