### ISSUE TITLE
Using github actions as ci

### ISSUE THREAD

**Issue by Smolevich** [TinkoffCreditSystems/Horarium#35]
Do you have plans use [Github Actions ](https://help.github.com/en/articles/about-github-actions) as CI?

**Comment by Bobreshovr** [comment]
No, I very like drone.io

**Comment by Smolevich** [comment]
Is it project for community? If it yes, Github Actions can be useful for users can make PR's and for another cases

**Comment by Bobreshovr** [comment]
Why is it useful? I have an open drone.io for it. Everyone can see the build in drone

**Comment by Smolevich** [comment]
Drone.io is outside ci, you can use Github Actions for ci in test mode, perhaps it will be more consistent to use ci and code in one system
